### ISSUE TITLE
KISA Open API를 통해서 IP주소 정보를 확인할 수 있는 기능 추가 검토

### ISSUE THREAD

**Issue by bjrambo** [xe-public/xe-module-loginlog#12]
https://github.com/soonjae/xe-module-loginlog

**Comment by bjrambo** [comment]
@soonjae https://github.com/xe-public/xe-module-loginlog/commit/bdebde6a69c76a4ffbbfa0fa297fb5b47439b24a with @bjrambo

**Comment by bjrambo** [comment]
일단 임시로 XML으로 코드가져오도록 햇고 XML parse 플러그인이 필요없도록 Json 으로 가져올 예정. (요즘은 Json 이 대세..)

**Comment by smaker** [comment]
@bjrambo 완성된 기능인가요?

**Comment by bjrambo** [comment]
@smaker 네
