### ISSUE TITLE
모듈 업데이트 시 오류가 있는 것 같음.

### ISSUE THREAD

**Issue by smaker** [xe-public/xe-module-loginlog#2]
기존 버전에서 업데이트를 한 경우 모듈 업데이트가 정상적으로 진행되지 않는 것 같음.
PHP 문법 상으로는 이상이 없는 것으로 봐서는 특정 환경에서 발생하는 버그인 것 같음.

참고: https://www.xetown.com/lakepark/303292#comment_303460

**Comment by mohaekr** [comment]
타임아웃을 늘려서 해결했습니다.! 타임아웃이 짧아서 생기는 현상이였네요.

**Comment by smaker** [comment]
@mohaekr 감사합니다. 모듈 업데이트를 할 때 타임아웃을 늘리면 될 것 같네요.
