### ISSUE TITLE
라이믹스 1.9 버전대와 호환 되지 않습니다.

### ISSUE THREAD

**Issue by onepang** [xe-public/xe-module-loginlog#4]
라이믹스 1.8버전까지는 괜찮은데

member.doLogin before 시점에 작동하는 트리거 중 에러메시지 없이 그냥 에러를 반환 합니다.

번거로우시겠지만 패치 부탁드립니다.

감사합니다.

**Comment by smaker** [comment]
최신 버전 (1.4.3)으로 업데이트 해보셔도 로그인이 안 되나요?
자세한 설치 환경을 알려주시면 확인해보겠습니다.

**Comment by misol** [comment]
@smaker 제가 연 이슈는 아니지만, 저도 로그인이 안되네요. FTP 를 이용해서 모듈을 삭제하고 나면 로그인이 됩니다. member 컨트롤러에서 한줄한줄 끊어가면서 보니까 doLogin before 트리거 부분에서 걸리길래 걸려있는 트리거 중에 loginlog 모듈 부터 없애보았는데, 바로 됩니다. 모듈을 다시 설치하면 로그인이 에러 메시지 없이 되지 않습니다.

제 설치 환경은 `Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.3` 입니다.

**Comment by misol** [comment]
오류가 나는 환경에서 문제를 해결하고 테스트 한 풀 리퀘스트를 제출합니다. https://github.com/xe-public/xe-module-loginlog/pull/5
